Repository mikrohash/decensored, pull requests merged in 2022-01, with the labels that each got.

#15 settings dialog markup
  app/css/style.css
  app/css/tailwind.css
  app/index.html
  app/js/helper.js
  app/js/init.js
  app/tailwind.config.js
  app/templates/bottombar.html
  app/templates/dialog.html
  app/templates/feed.html
  app/templates/overlay.html
Labels: enhancement

#20 refactor helper.js & init.js
  .gitignore
  app/js/helper.js
  app/js/init.js
  app/js/main.js
  app/package-lock.json
  app/templates/feed.html
Labels: refactoring

#23 added postInteractionBar
  app/css/tailwind.css
  app/js/helper.js
  app/js/main.js
Labels: enhancement

#27 feat: login functionality 2.0
  app/css/tailwind.css
  app/js/helper.js
  app/js/init.js
  app/js/main.js
  app/package-lock.json
  app/package.json
  app/templates/header.html
  app/templates/overlay.html
Labels: enhancement, UI/UX

#28 refactored signup/recovery animations
  app/css/tailwind.css
  app/js/helper.js
  app/js/main.js
  app/templates/feed.html
  app/templates/header.html
  app/templates/overlay.html
Labels: UI/UX

#30 Introduce Plugin Architecture
  app/index.html
  app/js/init.js
  app/js/main.js
  app/plugins/private_key_recovery/copy.html
  app/plugins/private_key_recovery/init.js
  app/plugins/private_key_recovery/recover.html
  app/plugins/private_key_recovery/toggle.html
  app/templates/inits.html
Labels: refactoring

#42 feat: add account approval
  app/index.html
  app/js/init.js
  app/js/main.js
  app/plugins/approve_account/approve_dialog.html
  app/plugins/approve_account/init.js
Labels: enhancement, UI/UX

#59 add get_latest_space_index()
  js/contract_abis.js
  js/spaces.js
Labels: enhancement

#68 feat: show / hide blocked users if they exist in feed
  js/post.js
  plugins/block_users/init.js
Labels: enhancement
